version: 2.1

workflows:
  main:
    jobs:
      - tests

jobs:
  tests:
    executor:
      name: node/default
      # The Node version here must be kept in sync with that in `package.json`.
      tag: '^18.18.0'
    steps:
      - checkout
      - run:
          name: Install NVM
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 18 # Install desired Node.js version
      - run:
          name: Use Node.js 18
          command: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 18
            node -v
      - node/install-packages:
          # `yarn install --frozen-lockfile` is run and cache is enabled by default for this orb configuration
          pkg-manager: yarn
      - run:
          command: yarn lint
          name: Run linting
      - run:
          command: yarn build
          name: Check build
      - run:
          command: yarn test:coverage
          name: Run Jest tests
      - run:
          command: yarn codecov
          name: Check code coverage changes

orbs:
  node: circleci/node@5.1.0
